/**
 * Audit module — Constants
 *
 * All shared constants for the health audit system.
 */

import type { AuditLevel } from "./types.js";

// ── Engineering Audit Constants ───────────────────────────────────────────────

export const ORPHAN_SEVERITY_THRESHOLD = 200;
export const OVERSIZED_WARNING_THRESHOLD = 1000;
export const OVERSIZED_INFO_THRESHOLD = 500;
export const MISSING_TEST_WARNING_THRESHOLD = 10;
export const ANY_TYPE_SEVERITY_THRESHOLD = 10;

// ── Source File Patterns ─────────────────────────────────────────────────────

export const SOURCE_SKIP_PATTERNS = [/\.test\.(ts|tsx|js|jsx)$/, /\.bench\.(ts|tsx|js|jsx)$/];

// ── Violation Keywords ───────────────────────────────────────────────────────
// Re-export from single source of truth in src/constants.ts
export { VIOLATION_KEYWORDS } from "../constants.js";

// ── Blocked Licenses ─────────────────────────────────────────────────────────

export const BLOCKED_LICENSES = ["GPL-3.0", "AGPL-3.0", "SSPL-1.0", "EUPL-1.1"];

// ── Security Detector Self-Paths ─────────────────────────────────────────────

export const SECURITY_DETECTOR_SELF_PATHS = [
  "src/health-auditor.ts",
  "src/audit/taint/",
  "src/audit/engineering-detectors.ts",
  "src/audit/engineering-detectors-security.ts",
  "src/audit/engineering-detectors-quality.ts",
  "src/audit/engineering-detectors-supply.ts",
];

// ── Complexity Thresholds ────────────────────────────────────────────────────

export const COMPLEXITY_WARNING_THRESHOLD = 15;
export const COMPLEXITY_CRITICAL_THRESHOLD = 25;

// ── Placeholder Names ────────────────────────────────────────────────────────

export const PLACEHOLDER_NAMES = new Set(["TEMPLATE.md", "RULE-TEMPLATE.json", ".gitkeep", "README.md"]);

// ── Detectors by Audit Level ─────────────────────────────────────────────────

export const DETECTORS_BY_LEVEL: Record<AuditLevel, string[]> = {
  quick: [
    "detectMissingDocs",
    "detectDatePlaceholders",
    "detectMissingGitignore",
    "detectMissingPackageJson",
    "detectStaleBuffer",
    "detectMaturityInconsistency",
  ],
  standard: [
    "detectMissingDocs",
    "detectDatePlaceholders",
    "detectMissingGitignore",
    "detectMissingPackageJson",
    "detectStaleBuffer",
    "detectMaturityInconsistency",
    "detectBrokenRefs",
    "detectBrokenDirRefs",
    "detectNonBacktickFileRefs",
    "detectEmptyDirs",
    "detectOrphanDirs",
    "detectBareWordRefs",
    "detectExtensionMismatch",
    "detectReportNaming",
    "detectTemplateDirRefs",
    "detectAdrCoverage",
    "detectUnreferencedDirs",
    "detectP0Inconsistency",
    "detectViolationHotspots",
    "detectOrphanModules",
    "detectComplexityHotspots",
    "detectTestCoverageGaps",
    "detectConsoleUsage",
    "detectEmptyCatchBlocks",
    "detectHighComplexity",
    "detectUnusedExports",
    "detectDeadCodePatterns",
    // Security detectors — promoted from code-review to standard (OWASP coverage)
    "detectHardcodedSecrets",
    "detectSQLInjection",
    "detectXSS",
    "detectUnsafeEval",
    "detectConsoleSecrets",
    "detectWeakCrypto",
    "detectInsecureHTTP",
    "detectPrototypePollution",
    "detectPathTraversal",
    "detectRegexDos",
    "detectUnsafeDeserialization",
    "detectDependencyConfusion",
    "detectTaintFlow",
    "detectConfigSecrets",
    "detectInsecureCORS",
    "detectInsecureCookies",
    "detectWeakRandomness",
    "detectAccessibilityGaps",
    "detectOrphanSkillFiles",
    "detectBrokenSkillManifestEntries",
  ],
  "code-review": [
    // All full-level detectors
    "detectMissingDocs",
    "detectDatePlaceholders",
    "detectMissingGitignore",
    "detectMissingPackageJson",
    "detectStaleBuffer",
    "detectMaturityInconsistency",
    "detectBrokenRefs",
    "detectBrokenDirRefs",
    "detectNonBacktickFileRefs",
    "detectEmptyDirs",
    "detectOrphanDirs",
    "detectBareWordRefs",
    "detectExtensionMismatch",
    "detectReportNaming",
    "detectTemplateDirRefs",
    "detectAdrCoverage",
    "detectUnreferencedDirs",
    "detectP0Inconsistency",
    "detectDeadRules",
    "detectViolationHotspots",
    "detectSystemMapMismatch",
    "detectBrokenCommands",
    "detectTripleMaturityScore",
    "detectEmptyStack",
    "detectScriptWiring",
    "detectAgentContractRefs",
    "detectBufferSchemaMismatch",
    "detectRuleTypo",
    "detectNumberingGap",
    "detectDocCountMismatch",
    "detectCrossDocP0Contradiction",
    "detectEmptyDataFiles",
    "detectPhantomRuleRefs",    "detectOrphanSkills",
    "detectOrphanSkillFiles",
    "detectBrokenSkillManifestEntries",
    "detectOrphanModules",
    "detectComplexityHotspots",
    "detectTestCoverageGaps",
    "detectConsoleUsage",
    "detectEmptyCatchBlocks",
    "detectHighComplexity",
    "detectUnusedExports",
    "detectDeadCodePatterns",
    "detectCircularDeps",
    "detectTestHealth",
    "detectLintIssues",
    "detectTypeSafetyIssues",
    "detectUnpinnedVersions",
    "detectMissingLockFile",
    "detectLockFileDrift",
    "detectPhantomDependencies",
    "detectDeprecatedPackages",
    "detectTaintFlow",
    "detectHardcodedSecrets",
    "detectSQLInjection",
    "detectXSS",
    "detectUnsafeEval",
    "detectConsoleSecrets",
    "detectWeakCrypto",
    "detectInsecureHTTP",
    "detectPrototypePollution",
    "detectPathTraversal",
    "detectRegexDos",
    "detectUnsafeDeserialization",
    "detectDependencyConfusion",
    "detectDependencyVulnerabilities",
    "detectIncompatibleLicenses",
    "detectConfigSecrets",
    // Git Intelligence (GIT-*)
    "detectCommitFormat",
    "detectBranchNaming",
    "detectDirectMainCommits",
    "detectForcePushes",
    "detectOrphanBranches",
    "detectCommitLanguage",
    "detectSecretsInGitHistory",
    "detectCommitWithoutGating",
    // Governance Enforcement (GOV-*)
    "detectIncompleteSessionClose",
    "detectMissingFeedback",
    "detectInvalidBacklogStates",
    "detectPlanFormat",
    "detectRuleExecutionCompliance",
    "detectPolicyStructure",
    "detectMissingPremortem",
    "detectMissingAdrForChanges",
    "detectDonePlanIntegrity",
    // Code Quality Intelligence (CQ-*)
    "detectJSDocCoverage",
    "detectUnsafeTypeAssertions",
    "detectUnreachableCode",
    "detectUnusedImports",
    "detectMagicNumbers",
    "detectLongParams",
    "detectDeepNesting",
    "detectDuplicateCode",
    "detectGodFunctions",
    "detectCoverageThreshold",
    // Architecture Validation (ARCH-*)
    "detectCleanArchitectureLayers",
    "detectSRPViolations",
    "detectDependencyInversion",
    "detectBarrelFileCycles",
    "detectModuleCoupling",
    "detectImportConsistency",
    "detectTestStructure",
    "detectAccessibilityGaps",
    "detectStaleVerification",
  ],
  enterprise: [
    // All code-review level detectors (99)
    "detectMissingDocs",
    "detectDatePlaceholders",
    "detectMissingGitignore",
    "detectMissingPackageJson",
    "detectStaleBuffer",
    "detectMaturityInconsistency",
    "detectBrokenRefs",
    "detectBrokenDirRefs",
    "detectNonBacktickFileRefs",
    "detectEmptyDirs",
    "detectOrphanDirs",
    "detectBareWordRefs",
    "detectExtensionMismatch",
    "detectReportNaming",
    "detectTemplateDirRefs",
    "detectAdrCoverage",
    "detectUnreferencedDirs",
    "detectP0Inconsistency",
    "detectDeadRules",
    "detectViolationHotspots",
    "detectSystemMapMismatch",
    "detectBrokenCommands",
    "detectTripleMaturityScore",
    "detectEmptyStack",
    "detectScriptWiring",
    "detectAgentContractRefs",
    "detectBufferSchemaMismatch",
    "detectRuleTypo",
    "detectNumberingGap",
    "detectDocCountMismatch",
    "detectCrossDocP0Contradiction",
    "detectEmptyDataFiles",
    "detectPhantomRuleRefs",    "detectOrphanSkills",
    "detectOrphanSkillFiles",
    "detectBrokenSkillManifestEntries",
    "detectOrphanModules",
    "detectComplexityHotspots",
    "detectTestCoverageGaps",
    "detectConsoleUsage",
    "detectEmptyCatchBlocks",
    "detectHighComplexity",
    "detectUnusedExports",
    "detectDeadCodePatterns",
    "detectCircularDeps",
    "detectTestHealth",
    "detectLintIssues",
    "detectTypeSafetyIssues",
    "detectUnpinnedVersions",
    "detectMissingLockFile",
    "detectLockFileDrift",
    "detectPhantomDependencies",
    "detectDeprecatedPackages",
    "detectTaintFlow",
    "detectHardcodedSecrets",
    "detectSQLInjection",
    "detectXSS",
    "detectUnsafeEval",
    "detectConsoleSecrets",
    "detectWeakCrypto",
    "detectInsecureHTTP",
    "detectPrototypePollution",
    "detectPathTraversal",
    "detectRegexDos",
    "detectUnsafeDeserialization",
    "detectDependencyConfusion",
    "detectDependencyVulnerabilities",
    "detectIncompatibleLicenses",
    "detectConfigSecrets",
    "detectCommitFormat",
    "detectBranchNaming",
    "detectDirectMainCommits",
    "detectForcePushes",
    "detectOrphanBranches",
    "detectCommitLanguage",
    "detectSecretsInGitHistory",
    "detectCommitWithoutGating",
    "detectIncompleteSessionClose",
    "detectMissingFeedback",
    "detectInvalidBacklogStates",
    "detectPlanFormat",
    "detectRuleExecutionCompliance",
    "detectPolicyStructure",
    "detectMissingPremortem",
    "detectMissingAdrForChanges",
    "detectDonePlanIntegrity",
    "detectJSDocCoverage",
    "detectUnsafeTypeAssertions",
    "detectUnreachableCode",
    "detectUnusedImports",
    "detectMagicNumbers",
    "detectLongParams",
    "detectDeepNesting",
    "detectDuplicateCode",
    "detectGodFunctions",
    "detectCoverageThreshold",
    "detectCleanArchitectureLayers",
    "detectSRPViolations",
    "detectDependencyInversion",
    "detectBarrelFileCycles",
    "detectModuleCoupling",
    "detectImportConsistency",
    "detectTestStructure",
    "detectAccessibilityGaps",
    "detectStaleVerification",
    // Enterprise: Product Strategy & Requirements (ENT-*)
    "detectVisionAlignment",
    "detectRoadmapConsistency",
    "detectKPICoverage",
    "detectOrphanRequirements",
    "detectRequirementTraceability",
    "detectAmbiguityPatterns",
    // Enterprise: Data Architecture & Persistence (ENT-DATA-*)
    "detectSchemaConsistency",
    "detectDataOwnership",
    "detectMissingMigrations",
    "detectIndexCoverage",
    // Enterprise: Reliability, Resilience & Concurrency (ENT-REL-*)
    "detectCircuitBreaker",
    "detectRetryPolicy",
    "detectTimeoutConfig",
    "detectHealthChecks",
    "detectGracefulDegradation",
    "detectRaceConditions",
    "detectDeadlockRisk",
    // Enterprise: Performance & Scalability (ENT-PERF-*)
    "detectNPlusOne",
    "detectMissingCaching",
    "detectStatefulServices",
    "detectMissingRateLimiting",
    "detectMissingTimeouts",
    // Enterprise: Observability (ENT-OBS-*)
    "detectMissingTracing",
    "detectLogStructure",
    "detectAlertCoverage",
    "detectMetricEndpoints",
    "detectMissingDashboard",
    "detectLogRetention",
    "detectDistributedLogging",
    "detectSLODefinitions",
    // Enterprise: Operations (ENT-OPS-*)
    "detectPipelineGaps",
    "detectRollbackCapability",
    "detectMissingRunbooks",
    "detectMonitoringGaps",
    "detectIncidentResponse",
    "detectDisasterRecovery",
    "detectCapacityPlanning",
    "detectChangeManagement",
    // Enterprise: Compliance (ENT-COMP-*)
    "detectOWASPTop10",
    "detectCWEMapping",
    "detectSOC2Controls",
    "detectNISTAlignment",
    "detectLGPDCompliance",
    "detectDataRetention",
    "detectConsentTracking",
    "detectSecretsInConfig",
    "detectEncryptionAtRest",
    "detectAccessControls",
    "detectAuditLogging",
    "detectComplianceReport",
    // Enterprise: Security Advanced (ENT-SEC-*)
    "detectSBOMCoverage",
    "detectDependencyProvenance",
    "detectTyposquatting",
    "detectLicenseConflicts",
    "detectTransitiveVulns",
    "detectMalwarePatterns",
    // Enterprise: Tech Debt (ENT-DEBT-*)
    "detectTechDebtCost",
    "detectTDR",
    "detectRemediationEffort",
    "detectDebtTrend",
    "detectHotspotFiles",
    "detectDebtByDomain",
    "detectROIRefactoring",
    "detectDebtAccumulationRate",
    // Enterprise: Supply Chain (ENT-SC-*)
    "detectSBOMExists",
    "detectSBOMCompleteness",
    "detectOutdatedDeps",
    "detectUnusedDeps",
    "detectMissingLockFile",
    "detectLockFileSync",
    "detectDuplicateDeps",
    "detectDepAuditStatus",
  ],
};

// ── Cross-File Detectors (require full project scan) ────────────────────────

/**
 * Detectors that require analysis of the entire project graph.
 * These must ALWAYS run on the full project, even in --changed mode.
 * Running them on a subset of files would produce false negatives.
 */
export const CROSS_FILE_ONLY_DETECTORS = new Set([
  "detectCircularDeps",
  "detectOrphanModules",
  "detectSystemMapMismatch",
  "detectModuleCoupling",
  "detectBarrelFileCycles",
  "detectDeadRules",
  "detectCrossDocP0Contradiction",
  "detectDocCountMismatch",
  "detectNumberingGap",
  "detectPhantomRuleRefs",
  "detectOrphanSkills",
  "detectOrphanSkillFiles",
  "detectBrokenSkillManifestEntries",
  "detectAgentContractRefs",
  // Enterprise cross-file detectors
  "detectSchemaConsistency",
  "detectDataOwnership",
  "detectPipelineGaps",
  "detectOWASPTop10",
  "detectCWEMapping",
  "detectSOC2Controls",
  "detectNISTAlignment",
  "detectLGPDCompliance",
  "detectSBOMCoverage",
  "detectLicenseConflicts",
  "detectTransitiveVulns",
  "detectMalwarePatterns",
  "detectTechDebtCost",
  "detectTDR",
  "detectDebtTrend",
  "detectDebtByDomain",
  "detectDebtAccumulationRate",
  "detectSBOMExists",
  "detectSBOMCompleteness",
  "detectDuplicateDeps",
  "detectDepAuditStatus",
]);
