import type { HealthIssue, SourceFileInfo, HistoryEntry } from "./types.js";
import { TaintAnalyzer } from "./taint/index.js";
import type { TaintIssue } from "./taint/types.js";

import {
  detectDeadRules,
  detectViolationHotspots,
  detectMissingDocs,
  detectOrphanDirs,
  detectStaleBuffer,
  detectDatePlaceholders,
  detectEmptyDirs,
  detectBrokenRefs,
  detectBrokenDirRefs,
  detectNonBacktickFileRefs,
  detectMissingGitignore,
  detectMissingPackageJson,
  detectMaturityInconsistency,
  detectAdrCoverage,
  detectUnreferencedDirs,
  detectReportNaming,
  detectBareWordRefs,
  detectTemplateDirRefs,
  detectExtensionMismatch,
  detectSystemMapMismatch,
  detectBrokenCommands,
  detectP0Inconsistency,
  detectTripleMaturityScore,
  detectEmptyStack,
  detectScriptWiring,
  detectAgentContractRefs,
  detectBufferSchemaMismatch,
  detectRuleTypo,
  detectNumberingGap,
  detectDocCountMismatch,
  detectCrossDocP0Contradiction,
  detectEmptyDataFiles,
  detectPhantomRuleRefs,
} from "../audit/governance-detectors.js";

import {
  detectOrphanModules,
  detectComplexityHotspots,
  detectTestCoverageGaps,
  detectConsoleUsage,
  detectEmptyCatchBlocks,
  detectHighComplexity,
  detectCircularDeps,
  detectUnusedExports,
  detectDeadCodePatterns,
  detectTestHealth,
  detectLintIssues,
  detectTypeSafetyIssues,
  detectUnpinnedVersions,
  detectMissingLockFile,
  detectLockFileDrift,
  detectPhantomDependencies,
  detectDeprecatedPackages,
  detectDependencyVulnerabilities,
  detectIncompatibleLicenses,
  detectConfigSecrets,
  detectHardcodedSecrets,
  detectSQLInjection,
  detectXSS,
  detectUnsafeEval,
  detectConsoleSecrets,
  detectWeakCrypto,
  detectInsecureHTTP,
  detectPrototypePollution,
  detectPathTraversal,
  detectRegexDos,
  detectUnsafeDeserialization,
  detectDependencyConfusion,
  detectInsecureCORS,
  detectInsecureCookies,
  detectWeakRandomness,
} from "../audit/engineering-detectors.js";

import {
  detectCommitFormat,
  detectBranchNaming,
  detectDirectMainCommits,
  detectForcePushes,
  detectOrphanBranches,
  detectCommitLanguage,
  detectSecretsInGitHistory,
  detectCommitWithoutGating,
} from "../audit/git-detectors.js";

import {
  detectIncompleteSessionClose,
  detectMissingFeedback,
  detectInvalidBacklogStates,
  detectPlanFormat,
  detectRuleExecutionCompliance,
  detectPolicyStructure,
  detectMissingPremortem,
  detectMissingAdrForChanges,
} from "../audit/governance-enforcement-detectors.js";

import {
  detectJSDocCoverage,
  detectUnsafeTypeAssertions,
  detectUnreachableCode,
  detectUnusedImports,
  detectMagicNumbers,
  detectLongParams,
  detectDeepNesting,
  detectDuplicateCode,
  detectGodFunctions,
  detectCoverageThreshold,
} from "../audit/code-quality-detectors.js";

import {
  detectCleanArchitectureLayers,
  detectSRPViolations,
  detectDependencyInversion,
  detectBarrelFileCycles,
  detectModuleCoupling,
  detectImportConsistency,
  detectTestStructure,
} from "../audit/architecture-detectors.js";

import {
  detectVisionAlignment,
  detectRoadmapConsistency,
  detectKPICoverage,
  detectOrphanRequirements,
  detectRequirementTraceability,
  detectAmbiguityPatterns,
} from "../audit/product-detectors.js";

import {
  detectSchemaConsistency,
  detectDataOwnership,
  detectMissingMigrations,
  detectIndexCoverage,
} from "../audit/data-architecture-detectors.js";

import {
  detectCircuitBreaker,
  detectRetryPolicy,
  detectTimeoutConfig,
  detectHealthChecks,
  detectGracefulDegradation,
  detectRaceConditions,
  detectDeadlockRisk,
} from "../audit/reliability-detectors.js";

import {
  detectNPlusOne,
  detectMissingCaching,
  detectStatefulServices,
  detectMissingRateLimiting,
  detectMissingTimeouts,
} from "../audit/performance-detectors.js";

import {
  detectMissingTracing,
  detectLogStructure,
  detectAlertCoverage,
  detectMetricEndpoints,
  detectMissingDashboard,
  detectLogRetention,
  detectDistributedLogging,
  detectSLODefinitions,
} from "../audit/observability-detectors.js";

import {
  detectPipelineGaps,
  detectRollbackCapability,
  detectMissingRunbooks,
  detectMonitoringGaps,
  detectIncidentResponse,
  detectDisasterRecovery,
  detectCapacityPlanning,
  detectChangeManagement,
} from "../audit/operations-detectors.js";

import {
  detectOWASPTop10,
  detectCWEMapping,
  detectSOC2Controls,
  detectNISTAlignment,
  detectLGPDCompliance,
  detectDataRetention,
  detectConsentTracking,
  detectSecretsInConfig,
  detectEncryptionAtRest,
  detectAccessControls,
  detectAuditLogging,
  detectComplianceReport,
} from "../audit/compliance-detectors.js";

import {
  detectSBOMCoverage,
  detectDependencyProvenance,
  detectTyposquatting,
  detectLicenseConflicts,
  detectTransitiveVulns,
  detectMalwarePatterns,
} from "../audit/security-advanced-detectors.js";

import {
  detectTechDebtCost,
  detectTDR,
  detectRemediationEffort,
  detectDebtTrend,
  detectHotspotFiles,
  detectDebtByDomain,
  detectROIRefactoring,
  detectDebtAccumulationRate,
} from "../audit/tech-debt-detectors.js";

import {
  detectSBOMExists,
  detectSBOMCompleteness,
  detectOutdatedDeps,
  detectUnusedDeps,
  detectLockFileSync,
  detectDuplicateDeps,
  detectDepAuditStatus,
} from "../audit/supply-chain-detectors.js";

export function buildDetectorMap(
  projectRoot: string,
  nexusDir: string,
  sourceFiles: SourceFileInfo[],
  rules: string[],
  history: HistoryEntry[]
): Record<string, () => HealthIssue[]> {
  return {
    detectDeadRules: () => detectDeadRules(rules, history),
    detectViolationHotspots: () => detectViolationHotspots(history),
    detectMissingDocs: () => detectMissingDocs(nexusDir),
    detectOrphanDirs: () => detectOrphanDirs(nexusDir),
    detectStaleBuffer: () => detectStaleBuffer(nexusDir),
    detectDatePlaceholders: () => detectDatePlaceholders(nexusDir),
    detectEmptyDirs: () => detectEmptyDirs(nexusDir),
    detectBrokenRefs: () => detectBrokenRefs(nexusDir),
    detectBrokenDirRefs: () => detectBrokenDirRefs(nexusDir),
    detectNonBacktickFileRefs: () => detectNonBacktickFileRefs(nexusDir),
    detectMissingGitignore: () => detectMissingGitignore(nexusDir),
    detectMaturityInconsistency: () => detectMaturityInconsistency(nexusDir),
    detectAdrCoverage: () => detectAdrCoverage(nexusDir),
    detectMissingPackageJson: () => detectMissingPackageJson(nexusDir),
    detectUnreferencedDirs: () => detectUnreferencedDirs(nexusDir),
    detectReportNaming: () => detectReportNaming(nexusDir),
    detectBareWordRefs: () => detectBareWordRefs(nexusDir),
    detectTemplateDirRefs: () => detectTemplateDirRefs(nexusDir),
    detectExtensionMismatch: () => detectExtensionMismatch(nexusDir),
    detectSystemMapMismatch: () => detectSystemMapMismatch(nexusDir),
    detectBrokenCommands: () => detectBrokenCommands(nexusDir),
    detectP0Inconsistency: () => detectP0Inconsistency(nexusDir),
    detectTripleMaturityScore: () => detectTripleMaturityScore(nexusDir),
    detectEmptyStack: () => detectEmptyStack(nexusDir),
    detectScriptWiring: () => detectScriptWiring(projectRoot, nexusDir),
    detectAgentContractRefs: () => detectAgentContractRefs(nexusDir),
    detectBufferSchemaMismatch: () => detectBufferSchemaMismatch(nexusDir),
    detectRuleTypo: () => detectRuleTypo(nexusDir),
    detectNumberingGap: () => detectNumberingGap(nexusDir),
    detectDocCountMismatch: () => detectDocCountMismatch(nexusDir),
    detectCrossDocP0Contradiction: () => detectCrossDocP0Contradiction(nexusDir),
    detectEmptyDataFiles: () => detectEmptyDataFiles(nexusDir),
    detectPhantomRuleRefs: () => detectPhantomRuleRefs(nexusDir),
    detectOrphanModules: () => detectOrphanModules(projectRoot, sourceFiles),
    detectComplexityHotspots: () => detectComplexityHotspots(projectRoot, sourceFiles),
    detectTestCoverageGaps: () => detectTestCoverageGaps(projectRoot, sourceFiles),
    detectConsoleUsage: () => detectConsoleUsage(projectRoot, sourceFiles),
    detectEmptyCatchBlocks: () => detectEmptyCatchBlocks(projectRoot, sourceFiles),
    detectHighComplexity: () => detectHighComplexity(projectRoot, sourceFiles),
    detectCircularDeps: () => detectCircularDeps(projectRoot, sourceFiles),
    detectUnusedExports: () => detectUnusedExports(projectRoot, sourceFiles),
    detectDeadCodePatterns: () => detectDeadCodePatterns(projectRoot, sourceFiles),
    detectTestHealth: () => detectTestHealth(projectRoot),
    detectLintIssues: () => detectLintIssues(projectRoot),
    detectTypeSafetyIssues: () => detectTypeSafetyIssues(projectRoot, sourceFiles),
    detectUnpinnedVersions: () => detectUnpinnedVersions(projectRoot),
    detectMissingLockFile: () => detectMissingLockFile(projectRoot),
    detectLockFileDrift: () => detectLockFileDrift(projectRoot),
    detectPhantomDependencies: () => detectPhantomDependencies(projectRoot, sourceFiles),
    detectDeprecatedPackages: () => detectDeprecatedPackages(projectRoot),
    detectDependencyVulnerabilities: () => detectDependencyVulnerabilities(projectRoot),
    detectIncompatibleLicenses: () => detectIncompatibleLicenses(projectRoot),
    detectConfigSecrets: () => detectConfigSecrets(projectRoot),
    detectHardcodedSecrets: () => detectHardcodedSecrets(projectRoot, sourceFiles),
    detectSQLInjection: () => detectSQLInjection(projectRoot, sourceFiles),
    detectXSS: () => detectXSS(projectRoot, sourceFiles),
    detectUnsafeEval: () => detectUnsafeEval(projectRoot, sourceFiles),
    detectConsoleSecrets: () => detectConsoleSecrets(projectRoot, sourceFiles),
    detectWeakCrypto: () => detectWeakCrypto(projectRoot, sourceFiles),
    detectInsecureHTTP: () => detectInsecureHTTP(projectRoot, sourceFiles),
    detectPrototypePollution: () => detectPrototypePollution(projectRoot, sourceFiles),
    detectPathTraversal: () => detectPathTraversal(projectRoot, sourceFiles),
    detectRegexDos: () => detectRegexDos(projectRoot, sourceFiles),
    detectUnsafeDeserialization: () => detectUnsafeDeserialization(projectRoot, sourceFiles),
    detectDependencyConfusion: () => detectDependencyConfusion(projectRoot, sourceFiles),
    detectInsecureCORS: () => detectInsecureCORS(projectRoot, sourceFiles),
    detectInsecureCookies: () => detectInsecureCookies(projectRoot, sourceFiles),
    detectWeakRandomness: () => detectWeakRandomness(projectRoot, sourceFiles),
    detectTaintFlow: () => {
      try {
        const analyzer = new TaintAnalyzer({ projectRoot });
        const taintIssues = analyzer.analyze();
        return taintIssues.map((ti: TaintIssue) => ({
          type: ("tainted_input" as const),
          severity: ti.severity,
          description: ti.description,
          location: ti.location,
          recommendation: ti.recommendation,
        }));
      } catch (err) {
        return [{
          type: "tainted_input" as const,
          severity: 2 as const,
          description: `Taint analysis não pôde ser executada — resultados de segurança incompletos: ${err instanceof Error ? err.message : String(err)}`,
          location: "taint-analyzer",
          recommendation: "Rodar com --debug para ver o erro completo",
        }] as HealthIssue[];
      }
    },
    detectCommitFormat: () => detectCommitFormat(projectRoot),
    detectBranchNaming: () => detectBranchNaming(projectRoot),
    detectDirectMainCommits: () => detectDirectMainCommits(projectRoot),
    detectForcePushes: () => detectForcePushes(projectRoot),
    detectOrphanBranches: () => detectOrphanBranches(projectRoot),
    detectCommitLanguage: () => detectCommitLanguage(projectRoot),
    detectSecretsInGitHistory: () => detectSecretsInGitHistory(projectRoot),
    detectCommitWithoutGating: () => detectCommitWithoutGating(projectRoot),
    detectIncompleteSessionClose: () => detectIncompleteSessionClose(nexusDir),
    detectMissingFeedback: () => detectMissingFeedback(nexusDir),
    detectInvalidBacklogStates: () => detectInvalidBacklogStates(nexusDir),
    detectPlanFormat: () => detectPlanFormat(nexusDir),
    detectRuleExecutionCompliance: () => detectRuleExecutionCompliance(nexusDir),
    detectPolicyStructure: () => detectPolicyStructure(nexusDir),
    detectMissingPremortem: () => detectMissingPremortem(nexusDir),
    detectMissingAdrForChanges: () => detectMissingAdrForChanges(nexusDir),
    detectJSDocCoverage: () => detectJSDocCoverage(projectRoot, sourceFiles),
    detectUnsafeTypeAssertions: () => detectUnsafeTypeAssertions(projectRoot, sourceFiles),
    detectUnreachableCode: () => detectUnreachableCode(projectRoot, sourceFiles),
    detectUnusedImports: () => detectUnusedImports(projectRoot, sourceFiles),
    detectMagicNumbers: () => detectMagicNumbers(projectRoot, sourceFiles),
    detectLongParams: () => detectLongParams(projectRoot, sourceFiles),
    detectDeepNesting: () => detectDeepNesting(projectRoot, sourceFiles),
    detectDuplicateCode: () => detectDuplicateCode(projectRoot, sourceFiles),
    detectGodFunctions: () => detectGodFunctions(projectRoot, sourceFiles),
    detectCoverageThreshold: () => detectCoverageThreshold(projectRoot),
    detectCleanArchitectureLayers: () => detectCleanArchitectureLayers(projectRoot, sourceFiles),
    detectSRPViolations: () => detectSRPViolations(projectRoot, sourceFiles),
    detectDependencyInversion: () => detectDependencyInversion(projectRoot, sourceFiles),
    detectBarrelFileCycles: () => detectBarrelFileCycles(projectRoot, sourceFiles),
    detectModuleCoupling: () => detectModuleCoupling(projectRoot, sourceFiles),
    detectImportConsistency: () => detectImportConsistency(projectRoot, sourceFiles),
    detectTestStructure: () => detectTestStructure(projectRoot),
    detectVisionAlignment: () => detectVisionAlignment(projectRoot),
    detectRoadmapConsistency: () => detectRoadmapConsistency(projectRoot),
    detectKPICoverage: () => detectKPICoverage(projectRoot),
    detectOrphanRequirements: () => detectOrphanRequirements(projectRoot, sourceFiles),
    detectRequirementTraceability: () => detectRequirementTraceability(projectRoot, sourceFiles),
    detectAmbiguityPatterns: () => detectAmbiguityPatterns(projectRoot),
    detectSchemaConsistency: () => detectSchemaConsistency(projectRoot, sourceFiles),
    detectDataOwnership: () => detectDataOwnership(projectRoot),
    detectMissingMigrations: () => detectMissingMigrations(projectRoot, sourceFiles),
    detectIndexCoverage: () => detectIndexCoverage(projectRoot, sourceFiles),
    detectCircuitBreaker: () => detectCircuitBreaker(projectRoot, sourceFiles),
    detectRetryPolicy: () => detectRetryPolicy(projectRoot, sourceFiles),
    detectTimeoutConfig: () => detectTimeoutConfig(projectRoot, sourceFiles),
    detectHealthChecks: () => detectHealthChecks(projectRoot),
    detectGracefulDegradation: () => detectGracefulDegradation(projectRoot, sourceFiles),
    detectRaceConditions: () => detectRaceConditions(projectRoot, sourceFiles),
    detectDeadlockRisk: () => detectDeadlockRisk(projectRoot, sourceFiles),
    detectNPlusOne: () => detectNPlusOne(projectRoot, sourceFiles),
    detectMissingCaching: () => detectMissingCaching(projectRoot, sourceFiles),
    detectStatefulServices: () => detectStatefulServices(projectRoot, sourceFiles),
    detectMissingRateLimiting: () => detectMissingRateLimiting(projectRoot, sourceFiles),
    detectMissingTimeouts: () => detectMissingTimeouts(projectRoot, sourceFiles),
    detectMissingTracing: () => detectMissingTracing(projectRoot, sourceFiles),
    detectLogStructure: () => detectLogStructure(projectRoot, sourceFiles),
    detectAlertCoverage: () => detectAlertCoverage(projectRoot, sourceFiles),
    detectMetricEndpoints: () => detectMetricEndpoints(projectRoot, sourceFiles),
    detectMissingDashboard: () => detectMissingDashboard(projectRoot, sourceFiles),
    detectLogRetention: () => detectLogRetention(projectRoot, sourceFiles),
    detectDistributedLogging: () => detectDistributedLogging(projectRoot, sourceFiles),
    detectSLODefinitions: () => detectSLODefinitions(projectRoot, sourceFiles),
    detectPipelineGaps: () => detectPipelineGaps(projectRoot, sourceFiles),
    detectRollbackCapability: () => detectRollbackCapability(projectRoot, sourceFiles),
    detectMissingRunbooks: () => detectMissingRunbooks(projectRoot, sourceFiles),
    detectMonitoringGaps: () => detectMonitoringGaps(projectRoot, sourceFiles),
    detectIncidentResponse: () => detectIncidentResponse(projectRoot, sourceFiles),
    detectDisasterRecovery: () => detectDisasterRecovery(projectRoot, sourceFiles),
    detectCapacityPlanning: () => detectCapacityPlanning(projectRoot, sourceFiles),
    detectChangeManagement: () => detectChangeManagement(projectRoot, sourceFiles),
    detectOWASPTop10: () => detectOWASPTop10(projectRoot, sourceFiles, []),
    detectCWEMapping: () => detectCWEMapping(projectRoot, sourceFiles, []),
    detectSOC2Controls: () => detectSOC2Controls(projectRoot, sourceFiles),
    detectNISTAlignment: () => detectNISTAlignment(projectRoot, sourceFiles),
    detectLGPDCompliance: () => detectLGPDCompliance(projectRoot, sourceFiles),
    detectDataRetention: () => detectDataRetention(projectRoot, sourceFiles),
    detectConsentTracking: () => detectConsentTracking(projectRoot, sourceFiles),
    detectSecretsInConfig: () => detectSecretsInConfig(projectRoot, sourceFiles),
    detectEncryptionAtRest: () => detectEncryptionAtRest(projectRoot, sourceFiles),
    detectAccessControls: () => detectAccessControls(projectRoot, sourceFiles),
    detectAuditLogging: () => detectAuditLogging(projectRoot, sourceFiles),
    detectComplianceReport: () => detectComplianceReport(projectRoot, sourceFiles),
    detectSBOMCoverage: () => detectSBOMCoverage(projectRoot, sourceFiles),
    detectDependencyProvenance: () => detectDependencyProvenance(projectRoot, sourceFiles),
    detectTyposquatting: () => detectTyposquatting(projectRoot, sourceFiles),
    detectLicenseConflicts: () => detectLicenseConflicts(projectRoot, sourceFiles),
    detectTransitiveVulns: () => detectTransitiveVulns(projectRoot, sourceFiles),
    detectMalwarePatterns: () => detectMalwarePatterns(projectRoot, sourceFiles),
    detectTechDebtCost: () => detectTechDebtCost(projectRoot, sourceFiles, []),
    detectTDR: () => detectTDR(projectRoot, sourceFiles, []),
    detectRemediationEffort: () => detectRemediationEffort(projectRoot, sourceFiles, []),
    detectDebtTrend: () => detectDebtTrend(projectRoot, sourceFiles),
    detectHotspotFiles: () => detectHotspotFiles(projectRoot, sourceFiles, []),
    detectDebtByDomain: () => detectDebtByDomain(projectRoot, sourceFiles, []),
    detectROIRefactoring: () => detectROIRefactoring(projectRoot, sourceFiles, []),
    detectDebtAccumulationRate: () => detectDebtAccumulationRate(projectRoot, sourceFiles),
    detectSBOMExists: () => detectSBOMExists(projectRoot, sourceFiles),
    detectSBOMCompleteness: () => detectSBOMCompleteness(projectRoot, sourceFiles),
    detectOutdatedDeps: () => detectOutdatedDeps(projectRoot, sourceFiles),
    detectUnusedDeps: () => detectUnusedDeps(projectRoot, sourceFiles),
    detectLockFileSync: () => detectLockFileSync(projectRoot, sourceFiles),
    detectDuplicateDeps: () => detectDuplicateDeps(projectRoot, sourceFiles),
    detectDepAuditStatus: () => detectDepAuditStatus(projectRoot, sourceFiles),
  };
}
