/**
 * shell-init.ts — Shell Integration Command
 *
 * Outputs shell hooks for bash/zsh that track terminal session lifecycle.
 * Users add `eval "$(nexus shell-init)"` to their .bashrc/.zshrc.
 *
 * PRINCIPLE: The system should know when a developer starts/stops working.
 */

import { Command } from "commander";

// ── Shell Script ─────────────────────────────────────────────────────────────

const SHELL_SCRIPT = [
  "# ── Nexus Shell Integration ──────────────────────────────────────────────────",
  "# Auto-generated by 'nexus shell-init'. Do not edit manually.",
  '# Add eval "$(nexus shell-init)" to your .bashrc/.zshrc.',
  "",
  '_nexus_session_id=""',
  '_nexus_session_start=""',
  "",
  "_nexus_hook_preexec() {",
  '  _nexus_session_start=$(date +%s)',
  "  command -v nexus >/dev/null 2>&1 && nexus feedback --outcome session-start 2>/dev/null &",
  "}",
  "",
  "_nexus_hook_precmd() {",
  '  if [ -n "$_nexus_session_start" ]; then',
  "    local _end=$(date +%s)",
  '    local _duration=$(( _end - _nexus_session_start ))',
  '    if [ "$_duration" -gt 5 ]; then',
  "      command -v nexus >/dev/null 2>&1 && nexus feedback --outcome session-end --duration \"$_duration\" 2>/dev/null &",
  "    fi",
  '    _nexus_session_start=""',
  "  fi",
  "}",
  "",
  "# Zsh hooks",
  'if [ -n "$ZSH_VERSION" ]; then',
  "  autoload -Uz add-zsh-hook 2>/dev/null",
  "  add-zsh-hook preexec _nexus_hook_preexec 2>/dev/null",
  "  add-zsh-hook precmd _nexus_hook_precmd 2>/dev/null",
  "# Bash hooks",
  'elif [ -n "$BASH_VERSION" ]; then',
  "  _nexus_preexec() {",
  "    _nexus_hook_preexec",
  "  }",
  "  _nexus_prompt_command() {",
  "    _nexus_hook_precmd",
  "  }",
  "  trap '_nexus_preexec' DEBUG 2>/dev/null",
  '  PROMPT_COMMAND="_nexus_prompt_command;${PROMPT_COMMAND:-}"',
  "fi",
  "",
  "# ── End Nexus Shell Integration ──────────────────────────────────────────────",
].join("\n");

// ── Command ──────────────────────────────────────────────────────────────────

export const shellInitCommand = new Command("shell-init")
  .description("Output shell hooks for session tracking (add eval to .bashrc/.zshrc)")
  .action(() => {
    process.stdout.write(SHELL_SCRIPT + "\n");
  });
