/**
 * capability-engine.ts — Capability Engine: First-Class Entity System
 *
 * Manages capabilities as first-class entities with identity, state,
 * dependencies, policies, rules, skills, templates, recommendations,
 * and metrics. Growth occurs through capability activation, not command addition.
 *
 * PRINCIPLE: The system grows by unlocking capabilities, not by adding commands.
 */

import { existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { getEventBus, type NexusEventType } from "./event-bus.js";
import {
  CAPABILITIES,
  type Capability,
  type CapabilityInfo,
  type MaturityDimensions,
  type MaturityProfile,
} from "./maturity-profile.js";
import type { EngineeringState } from "./engineering-state.js";

// ── Types ───────────────────────────────────────────────────────────────────

/** Capability maturity level. */
export type CapabilityMaturity =
  | "dormant"     // Not installed
  | "installed"   // Files present but not configured
  | "configured"  // Configured and basic policies active
  | "active"      // Fully active with rules and automations
  | "optimized";  // Continuously improving through feedback

/** A capability entity with full metadata. */
export interface CapabilityEntity {
  /** Unique identifier. */
  id: Capability;
  /** Display name. */
  name: string;
  /** Description. */
  description: string;
  /** Current maturity level. */
  maturity: CapabilityMaturity;
  /** Maturity score (0-100). */
  maturityScore: number;
  /** Dimensions this capability contributes to. */
  dimensions: Partial<Record<keyof MaturityDimensions, number>>;
  /** Dependencies (other capabilities required). */
  dependencies: Capability[];
  /** Active policies (rules) within this capability. */
  activePolicies: string[];
  /** Active skills within this capability. */
  activeSkills: string[];
  /** Templates available in this capability. */
  templates: string[];
  /** Recommendations generated by this capability. */
  recommendations: string[];
  /** Metrics tracked by this capability. */
  metrics: CapabilityMetrics;
  /** Whether this capability is always installed. */
  alwaysInstalled: boolean;
  /** Whether this capability is currently installed. */
  isInstalled: boolean;
  /** Files belonging to this capability. */
  files: string[];
}

/** Metrics tracked per capability. */
export interface CapabilityMetrics {
  /** Number of assets this capability owns. */
  assetCount: number;
  /** Number of active rules. */
  ruleCount: number;
  /** Number of active policies. */
  policyCount: number;
  /** Health score of this capability (0-100). */
  healthScore: number;
  /** Last time this capability was updated. */
  lastUpdated: string;
  /** Number of times this capability has been referenced. */
  referenceCount: number;
}

/** Result of capability engine evaluation. */
export interface CapabilityEngineResult {
  /** Timestamp of evaluation. */
  evaluatedAt: string;
  /** All capability entities. */
  capabilities: CapabilityEntity[];
  /** Capabilities by maturity level. */
  byMaturity: Record<CapabilityMaturity, Capability[]>;
  /** Overall capability score (0-100). */
  overallScore: number;
  /** Recommendations for capability evolution. */
  recommendations: CapabilityRecommendation[];
  /** Summary. */
  summary: string;
}

/** A recommendation for capability evolution. */
export interface CapabilityRecommendation {
  capability: Capability;
  action: "activate" | "upgrade" | "configure" | "optimize" | "deprecate";
  priority: "urgent" | "high" | "medium" | "low";
  reason: string;
  expectedImpact: string;
  dependencies: Capability[];
}

// ── Capability Maturity Detection ───────────────────────────────────────────

/** Detect maturity level of a capability. */
function detectCapabilityMaturity(
  capability: Capability,
  nexusDir: string,
  installedCapabilities: Capability[]
): { level: CapabilityMaturity; score: number } {
  if (!installedCapabilities.includes(capability)) {
    return { level: "dormant", score: 0 };
  }

  const capInfo = CAPABILITIES.find((c) => c.id === capability);
  if (!capInfo) return { level: "dormant", score: 0 };

  let score = 20; // Base score for being installed

  // Check for files
  const hasFiles = checkCapabilityFiles(capability, nexusDir);
  if (hasFiles) score += 20;

  // Check for rules/policies
  const hasRules = checkCapabilityRules(capability, nexusDir);
  if (hasRules) score += 20;

  // Check for skills
  const hasSkills = checkCapabilitySkills(capability, nexusDir);
  if (hasSkills) score += 15;

  // Check for templates
  const hasTemplates = checkCapabilityTemplates(capability, nexusDir);
  if (hasTemplates) score += 10;

  // Check for metrics/reports
  const hasMetrics = checkCapabilityMetrics(capability, nexusDir);
  if (hasMetrics) score += 15;

  // Determine maturity level
  let level: CapabilityMaturity;
  if (score >= 80) level = "optimized";
  else if (score >= 60) level = "active";
  else if (score >= 40) level = "configured";
  else level = "installed";

  return { level, score: Math.min(100, score) };
}

function checkCapabilityFiles(capability: Capability, nexusDir: string): boolean {
  const mapping = getCapabilityFilesForEngine(capability);
  return mapping.some((f) => existsSync(join(nexusDir, f)));
}

function checkCapabilityRules(capability: Capability, nexusDir: string): boolean {
  const rulesDir = join(nexusDir, "governance", "rules");
  if (!existsSync(rulesDir)) return false;

  const ruleFiles = readdirSync(rulesDir).filter((f) => f.endsWith(".json"));
  for (const file of ruleFiles) {
    try {
      const content = JSON.parse(readFileSync(join(rulesDir, file), "utf-8"));
      if (content.tags && content.tags.includes(capability)) return true;
    } catch {
      // skip
    }
  }
  return false;
}

function checkCapabilitySkills(capability: Capability, nexusDir: string): boolean {
  const skillsDir = join(nexusDir, "docs", "skills");
  if (!existsSync(skillsDir)) return false;

  return readdirSync(skillsDir).filter((f) => f.endsWith(".md")).length > 0;
}

function checkCapabilityTemplates(capability: Capability, nexusDir: string): boolean {
  const templatesDir = join(nexusDir, "templates");
  if (!existsSync(templatesDir)) return false;

  return readdirSync(templatesDir).filter(
    (f) => f.endsWith(".md") || f.endsWith(".yaml")
  ).length > 0;
}

function checkCapabilityMetrics(capability: Capability, nexusDir: string): boolean {
  const reportsDir = join(nexusDir, "reports");
  if (!existsSync(reportsDir)) return false;

  return readdirSync(reportsDir).filter((f) => f.endsWith(".json")).length > 0;
}

function getCapabilityFilesForEngine(capability: Capability): string[] {
  const fileMap: Record<Capability, string[]> = {
    core: ["opencode.json", "docs/AGENTS.md"],
    knowledge: ["docs/skills/", "docs/AGENTS.md"],
    architecture: ["docs/adrs/", "docs/sdr/", "docs/plans/"],
    governance: ["governance/WORKFLOW.md", "governance/context/"],
    ai: ["governance/agents/", "cognition/"],
    quality: ["scripts/validate-session.ts"],
    metrics: ["reports/"],
    operations: ["scripts/close-session.ts", "docs/runbooks/"],
    compliance: ["docs/FORBIDDEN_OPERATIONS.md", "docs/DESDO.md"],
  };
  return fileMap[capability] || [];
}

// ── Capability Entity Builder ───────────────────────────────────────────────

/** Build a full capability entity. */
function buildCapabilityEntity(
  capInfo: CapabilityInfo,
  nexusDir: string,
  installedCapabilities: Capability[],
  assets: Array<{ type: string; path: string }>,
  maturityScore: number
): CapabilityEntity {
  const isInstalled = installedCapabilities.includes(capInfo.id);
  const { level, score } = detectCapabilityMaturity(capInfo.id, nexusDir, installedCapabilities);

  // Count assets belonging to this capability
  const capabilityAssets = assets.filter((a) => {
    const mapping = getCapabilityFilesForEngine(capInfo.id);
    return mapping.some((m) => a.path.startsWith(m.replace(/\/$/, "")));
  });

  // Collect active policies, skills, templates
  const activePolicies = collectCapabilityPolicies(capInfo.id, nexusDir);
  const activeSkills = collectCapabilitySkills(capInfo.id, nexusDir);
  const templates = collectCapabilityTemplates(capInfo.id, nexusDir);

  return {
    id: capInfo.id,
    name: capInfo.name,
    description: capInfo.description,
    maturity: level,
    maturityScore: score,
    dimensions: capInfo.dimensions,
    dependencies: capInfo.requires,
    activePolicies,
    activeSkills,
    templates,
    recommendations: [],
    metrics: {
      assetCount: capabilityAssets.length,
      ruleCount: activePolicies.length,
      policyCount: activePolicies.length,
      healthScore: score,
      lastUpdated: new Date().toISOString(),
      referenceCount: 0,
    },
    alwaysInstalled: capInfo.alwaysInstalled,
    isInstalled,
    files: getCapabilityFilesForEngine(capInfo.id),
  };
}

function collectCapabilityPolicies(capability: Capability, nexusDir: string): string[] {
  const policies: string[] = [];
  const rulesDir = join(nexusDir, "governance", "rules");
  if (!existsSync(rulesDir)) return policies;

  const ruleFiles = readdirSync(rulesDir).filter((f) => f.endsWith(".json"));
  for (const file of ruleFiles) {
    try {
      const content = JSON.parse(readFileSync(join(rulesDir, file), "utf-8"));
      if (content.tags && content.tags.includes(capability)) {
        policies.push(content.id || file.replace(".json", ""));
      }
    } catch {
      // skip
    }
  }
  return policies;
}

function collectCapabilitySkills(capability: Capability, nexusDir: string): string[] {
  const skills: string[] = [];
  const skillsDir = join(nexusDir, "docs", "skills");
  if (!existsSync(skillsDir)) return skills;

  const skillFiles = readdirSync(skillsDir).filter((f) => f.endsWith(".md"));
  for (const file of skillFiles) {
    skills.push(file.replace(".md", ""));
  }
  return skills;
}

function collectCapabilityTemplates(capability: Capability, nexusDir: string): string[] {
  const templates: string[] = [];
  const templatesDir = join(nexusDir, "templates");
  if (!existsSync(templatesDir)) return templates;

  const templateFiles = readdirSync(templatesDir).filter(
    (f) => f.endsWith(".md") || f.endsWith(".yaml")
  );
  for (const file of templateFiles) {
    templates.push(file);
  }
  return templates;
}

// ── Recommendation Generator ────────────────────────────────────────────────

/** Generate recommendations for capability evolution. */
function generateCapabilityRecommendations(
  capabilities: CapabilityEntity[],
  dimensions: MaturityDimensions
): CapabilityRecommendation[] {
  const recommendations: CapabilityRecommendation[] = [];

  for (const cap of capabilities) {
    if (cap.maturity === "dormant") {
      // Check if dimensions warrant activation
      let relevance = 0;
      let weightCount = 0;
      for (const [dim, weight] of Object.entries(cap.dimensions)) {
        const dimScore = dimensions[dim as keyof MaturityDimensions];
        relevance += dimScore * weight;
        weightCount += weight;
      }

      if (weightCount > 0 && relevance / weightCount >= 25) {
        // Check dependencies
        const depsMet = cap.dependencies.every((dep) =>
          capabilities.find((c) => c.id === dep)?.isInstalled
        );

        if (depsMet) {
          recommendations.push({
            capability: cap.id,
            action: "activate",
            priority: "high",
            reason: `Maturity dimensions warrant ${cap.name} capability`,
            expectedImpact: `Adds ${cap.name.toLowerCase()} governance to the project`,
            dependencies: cap.dependencies,
          });
        }
      }
    } else if (cap.maturity === "installed" || cap.maturity === "configured") {
      if (cap.maturityScore < 60) {
        recommendations.push({
          capability: cap.id,
          action: "configure",
          priority: "medium",
          reason: `${cap.name} is ${cap.maturity} but not fully configured`,
          expectedImpact: "Improves capability effectiveness",
          dependencies: [],
        });
      }
    } else if (cap.maturity === "active") {
      if (cap.maturityScore < 80) {
        recommendations.push({
          capability: cap.id,
          action: "optimize",
          priority: "low",
          reason: `${cap.name} can be further optimized`,
          expectedImpact: "Maximizes capability value",
          dependencies: [],
        });
      }
    }
  }

  return recommendations.sort((a, b) => {
    const priorityOrder = { urgent: 0, high: 1, medium: 2, low: 3 };
    return priorityOrder[a.priority] - priorityOrder[b.priority];
  });
}

// ── Main Engine ─────────────────────────────────────────────────────────────

/** Evaluate all capabilities and return engine result. */
export function evaluateCapabilities(
  state: EngineeringState,
  nexusDir: string
): CapabilityEngineResult {
  const capabilities: CapabilityEntity[] = [];

  for (const capInfo of CAPABILITIES) {
    const entity = buildCapabilityEntity(
      capInfo,
      nexusDir,
      state.capabilities,
      state.assets,
      state.maturity?.overallScore ?? 0
    );
    capabilities.push(entity);
  }

  // Group by maturity
  const byMaturity: Record<CapabilityMaturity, Capability[]> = {
    dormant: [],
    installed: [],
    configured: [],
    active: [],
    optimized: [],
  };

  for (const cap of capabilities) {
    byMaturity[cap.maturity].push(cap.id);
  }

  // Overall score: weighted average of capability scores
  const totalScore = capabilities.reduce((sum, c) => sum + c.maturityScore, 0);
  const overallScore = capabilities.length > 0
    ? Math.round(totalScore / capabilities.length)
    : 0;

  // Generate recommendations
  const dimensions = state.maturity?.dimensions ?? {
    architecture: 0,
    governance: 0,
    quality: 0,
    automation: 0,
    ai: 0,
    documentation: 0,
    observability: 0,
  };
  const recommendations = generateCapabilityRecommendations(capabilities, dimensions);

  // Build summary
  const parts: string[] = [];
  parts.push(`${capabilities.length} capabilities evaluated.`);
  const activeCount = byMaturity.active.length + byMaturity.optimized.length;
  parts.push(`${activeCount} active/optimized.`);
  const dormantCount = byMaturity.dormant.length;
  if (dormantCount > 0) parts.push(`${dormantCount} dormant.`);
  parts.push(`Score: ${overallScore}/100.`);
  if (recommendations.length > 0) parts.push(`${recommendations.length} recommendation(s).`);

  return {
    evaluatedAt: new Date().toISOString(),
    capabilities,
    byMaturity,
    overallScore,
    recommendations,
    summary: parts.join(" "),
  };
}

// ── Persistence ────────────────────────────────────────────────────────────

/** Save capability engine result to disk. */
export function saveCapabilityEngineResult(
  nexusDir: string,
  result: CapabilityEngineResult
): void {
  const filePath = join(nexusDir, "capability-engine.json");
  writeFileSync(filePath, JSON.stringify(result, null, 2), "utf-8");
}

/** Load capability engine result from disk. */
export function loadCapabilityEngineResult(
  nexusDir: string
): CapabilityEngineResult | null {
  const filePath = join(nexusDir, "capability-engine.json");
  if (!existsSync(filePath)) return null;

  try {
    const content = readFileSync(filePath, "utf-8");
    return JSON.parse(content) as CapabilityEngineResult;
  } catch {
    return null;
  }
}

// ── Event Integration ──────────────────────────────────────────────────────

/** Initialize capability engine event subscriptions. */
export function initializeCapabilityEngine(
  projectRoot: string,
  nexusDir: string
): void {
  const bus = getEventBus();

  // On capability install, re-evaluate
  bus.subscribe("capability.installed", () => {
    import("./engineering-state.js").then((mod) => {
      const state = mod.consolidateEngineeringState(projectRoot, nexusDir);
      const result = evaluateCapabilities(state, nexusDir);
      saveCapabilityEngineResult(nexusDir, result);
    }).catch(() => {
      // skip
    });
  });
}

// ── Report ─────────────────────────────────────────────────────────────────

/** Generate human-readable report from capability engine result. */
export function capabilityEngineToText(result: CapabilityEngineResult): string {
  const lines: string[] = [];

  lines.push("# Capability Engine Report");
  lines.push(`Evaluated: ${result.evaluatedAt}`);
  lines.push(`Overall Score: ${result.overallScore}/100`);
  lines.push("");

  // By maturity
  lines.push("## By Maturity Level");
  for (const [level, caps] of Object.entries(result.byMaturity)) {
    if (caps.length > 0) {
      lines.push(`  ${level}: ${caps.join(", ")}`);
    }
  }
  lines.push("");

  // Capabilities detail
  lines.push("## Capabilities");
  for (const cap of result.capabilities) {
    const statusIcon = cap.isInstalled ? "✓" : "○";
    lines.push(`  ${statusIcon} ${cap.name} (${cap.maturity}: ${cap.maturityScore}/100)`);
    if (cap.activePolicies.length > 0) {
      lines.push(`    Policies: ${cap.activePolicies.join(", ")}`);
    }
    if (cap.activeSkills.length > 0) {
      lines.push(`    Skills: ${cap.activeSkills.join(", ")}`);
    }
  }
  lines.push("");

  // Recommendations
  if (result.recommendations.length > 0) {
    lines.push("## Recommendations");
    for (const rec of result.recommendations) {
      lines.push(`  [${rec.priority.toUpperCase()}] ${rec.action} ${rec.capability}`);
      lines.push(`    Reason: ${rec.reason}`);
      lines.push(`    Impact: ${rec.expectedImpact}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
